IC2: Add converter for reactor components to get stored heat.
GTNewHorizons/OpenComputers pull request #126
Opened 2024-07-09 13:19 UTC by Engineer12798

With coolant cells and other heat storing items, there is no uniform way in game to extract the heat stored in these items. To do so, would require parsing the NBT of the item stack, which is difficult enough as is, but would also require reading different NBT tags depending on the mod the item came from. To resolve this problem, this PR adds in a converter which will get the stored heat of any item implementing `IReactorComponent`.

The way the PR works may be jank and not work with some components. There may exist cases where the stored heat and max heat of a component are dependent on the reactor context, which this converter does not provide when trying to get the stored heat.

2024-07-09 14:31 UTC, OneEyeMaker commented
Despite this implementation will work in certain circumstances, one doesn't solve mentioned issue properly. (Even more, one can cause an exception).

Instead I suggest to extend [`DriverReactor`](https://github.com/GTNewHorizons/OpenComputers/blob/master/src/main/scala/li/cil/oc/integration/ic2/DriverReactor.java) and [`DriverReactorChamber`](https://github.com/GTNewHorizons/OpenComputers/blob/master/src/main/scala/li/cil/oc/integration/ic2/DriverReactorChamber.java) classes and add necessary methods there.

And only then add your implementation for handling components outside reactor. Make sure to mark it *explicit* and *unsafe* so players understand what they do. Currently, from player's perspective, these properties you added look like regular (*safe*) ones.

2024-07-10 17:30 UTC, OneEyeMaker requested changes
Good job! Now this feature is almost complete.
Just find a way to tell players that original approach is not 100% reliable.

2024-07-10 17:30 UTC, OneEyeMaker commented on src/main/scala/li/cil/oc/integration/ic2/ConverterReactorHeatStorage.java
> +                	output.put("maxHeat", maxHeat);
Please, rename these fields to mark that ones are not 100% reliable. Maybe to `heatUnsafe` or something similar.

2024-07-10 23:09 UTC, Ktmi commented on src/main/scala/li/cil/oc/integration/ic2/ConverterReactorHeatStorage.java
> +                	output.put("maxHeat", maxHeat);
I'm just going to drop the converter for the item. This is going to be used primarily in the context of reactors anyway, so it shouldn't be too big a deal to to not have the item coverter. And even if user's didn't use the unsafe variable, the converter would still run whenever getting the item stack, regardless of reading the variable or not.

2024-07-10 23:25 UTC, Engineer12798 commented on src/main/scala/li/cil/oc/integration/ic2/ConverterReactorHeatStorage.java
> +                	output.put("maxHeat", maxHeat);
Got rid of the converter. This is going to be primarily used with reactors anyway.

2024-07-11 06:10 UTC, OneEyeMaker approved these changes

2024-07-11 06:23 UTC, merged